### ISSUE TITLE
error TS2345

### ISSUE THREAD

**Issue by ericvanderlinden** [HuygensING/timbuctoo-gui#28]
Does this have to do with version of NPM modules?

Failed to compile
./src/services/CollectionArgumentsCreator.ts
(121,81): error TS2345: Argument of type 'string | string[]' is not assignable to parameter of type 'string'.
  Type 'string[]' is not assignable to type 'string'.
This error occurred during the build time and cannot be dismissed.

**Comment by jauco** [comment]
It might be the version of npm. Could you try with the latest node?

**Comment by ericvanderlinden** [comment]
I have the latest... 
So I went to the page and cast search to string with `<string>.` And then I got the next error...
I got something with no property width so I commented the line out with
`/*width: ${props => props.width || '100%'*/};`

And then I got a new error...
./src/components/About.tsx
(26,9): error TS2554: Expected 1-2 arguments, but got 0.

Any ideas why?

**Comment by ericvanderlinden** [comment]
still some error but most of them gone with updaten npm modules.
I'm looking at them now.
Sorry, python guy... no experience with javascript apps.

**Comment by ericvanderlinden** [comment]
Two error left:
1)
Failed to load http://127.0.0.1:8080/static/graphiql: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:3000' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

2)
Failed to compile
./src/components/form/VariableFieldRenderer.tsx
(160,29): error TS2352: Type '{ type: "IMAGE"; id: number; subComponents?: [LeafComponentConfig, LeafComponentConfig] | undefin...' cannot be converted to type 'PathComponentConfig'.
  Type '{ type: "PATH"; id: number; value?: string | undefined; formatter: { type: string; name: Formatte...' is not comparable to type 'PathComponentConfig'.
    Object literal may only specify known properties, and 'id' does not exist in type 'PathComponentConfig'.

**Comment by ichsaras** [comment]
Hi Eric, 
1) I think you're referring to http://127.0.0.1:8080 directly. Make sure to connect the gui to http://127.0.0.1:8080/v5/graphql

2) Could you share the version of NodeJs (`node --version`) and the version of npm (`npm --version`) you're running? An older version or mismatch in versions could cause this.
P.S: The VariableFieldRenderer no longer exists, could you pull the latest develop?

**Comment by ericvanderlinden** [comment]
Well this is a lot better but still some errors
versions:
ericvanderlinden$ node --version
v8.9.1
ericvanderlinden$ npm --version
5.5.1

get a lot of these seems they are not installed in NPM?
npm WARN enzyme-adapter-react-16@1.1.0 requires a peer of enzyme@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-code-generator@0.5.5 requires a peer of graphql@~0.10.0 | ~0.9.0 | ~0.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-subscriptions@0.3.1 requires a peer of graphql@^0.7.0 || ^0.8.0 || ^0.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN redux-connect@5.1.0 requires a peer of react@15.x.x but none is installed. You must install peer dependencies yourself.
npm WARN redux-connect@5.1.0 requires a peer of react-router@~2.x.x || ~3.x.x but none is installed. You must install peer dependencies yourself.
npm WARN why-did-you-update@0.0.8 requires a peer of react@^15.0 || 0.14.x but none is installed. You must install peer dependencies yourself.

still errors:
proxyConsole.js:54 ./src/components/form/fields/Select.tsx
(57,49): error TS2339: Property 'disabled' does not exist on type 'ThemedStyledProps<DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>, ThemeProps>'.
__stack_frame_overlay_proxy_console__ @ proxyConsole.js:54
handleErrors @ webpackHotDevClient.js:166
./node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:199
./node_modules/sockjs-client/lib/event/eventtarget.js.EventTarget.dispatchEvent @ eventtarget.js:51
(anonymous) @ main.js:274
./node_modules/sockjs-client/lib/main.js.SockJS._transportMessage @ main.js:272
./node_modules/sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:50
WebSocketTransport.ws.onmessage @ websocket.js:35
proxyConsole.js:54 ./src/components/form/fields/Select.tsx
(171,28): error TS2559: Type '{ disabled: boolean | undefined; }' has no properties in common with type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ThemedOuterStyledProps<DetailedHTMLProps...'.
__stack_frame_overlay_proxy_console__ @ proxyConsole.js:54
handleErrors @ webpackHotDevClient.js:166
./node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:199
./node_modules/sockjs-client/lib/event/eventtarget.js.EventTarget.dispatchEvent @ eventtarget.js:51
(anonymous) @ main.js:274
./node_modules/sockjs-client/lib/main.js.SockJS._transportMessage @ main.js:272
./node_modules/sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:50
WebSocketTransport.ws.onmessage @ websocket.js:35
proxyConsole.js:54 ./src/components/form/ComponentFields.tsx
(81,85): error TS2345: Argument of type '{ referencePath: string[][]; id: number; type: "IMAGE"; subComponents?: [LeafComponentConfig, Lea...' is not assignable to parameter of type 'ComponentConfig'.
  Type '{ referencePath: string[][]; id: number; type: "IMAGE"; subComponents?: [LeafComponentConfig, Lea...' is not assignable to type 'ComponentConfig'.
    Object literal may only specify known properties, and 'referencePath' does not exist in type 'ImageComponentConfig'.
__stack_frame_overlay_proxy_console__ @ proxyConsole.js:54
handleErrors @ webpackHotDevClient.js:166
./node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:199
./node_modules/sockjs-client/lib/event/eventtarget.js.EventTarget.dispatchEvent @ eventtarget.js:51
(anonymous) @ main.js:274
./node_modules/sockjs-client/lib/main.js.SockJS._transportMessage @ main.js:272
./node_modules/sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:50
WebSocketTransport.ws.onmessage @ websocket.js:35
proxyConsole.js:54 ./src/components/content/ContentImage.tsx
(20,29): error TS2339: Property 'width' does not exist on type 'ThemedStyledProps<DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>, ThemeProps>'.
__stack_frame_overlay_proxy_console__ @ proxyConsole.js:54
handleErrors @ webpackHotDevClient.js:166
./node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:199
./node_modules/sockjs-client/lib/event/eventtarget.js.EventTarget.dispatchEvent @ eventtarget.js:51
(anonymous) @ main.js:274
./node_modules/sockjs-client/lib/main.js.SockJS._transportMessage @ main.js:272
./node_modules/sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:50
WebSocketTransport.ws.onmessage @ websocket.js:35
proxyConsole.js:54 ./src/components/content/ContentImage.tsx
(24,19): error TS2339: Property 'type' does not exist on type 'ThemedStyledProps<DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>, ThemeProps>'.
__stack_frame_overlay_proxy_console__ @ proxyConsole.js:54
handleErrors @ webpackHotDevClient.js:166
./node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:199
./node_modules/sockjs-client/lib/event/eventtarget.js.EventTarget.dispatchEvent @ eventtarget.js:51
(anonymous) @ main.js:274
./node_modules/sockjs-client/lib/main.js.SockJS._transportMessage @ main.js:272
./node_modules/sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:50
WebSocketTransport.ws.onmessage @ websocket.js:35
proxyConsole.js:54 ./src/components/ProgressBar.tsx
(23,29): error TS2339: Property 'width' does not exist on type 'ThemedStyledProps<DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>, ThemeProps>'.
__stack_frame_overlay_proxy_console__ @ proxyConsole.js:54
handleErrors @ webpackHotDevClient.js:166
./node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:199
./node_modules/sockjs-client/lib/event/eventtarget.js.EventTarget.dispatchEvent @ eventtarget.js:51
(anonymous) @ main.js:274
./node_modules/sockjs-client/lib/main.js.SockJS._transportMessage @ main.js:272
./node_modules/sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:50
WebSocketTransport.ws.onmessage @ websocket.js:35
proxyConsole.js:54 ./src/components/ProgressBar.tsx
(71,18): error TS2339: Property 'width' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ThemedOuterStyledProps<DetailedHTMLProps...'.

**Comment by jauco** [comment]
apparently you're working at the huygens? Just drop by at room 3.09 at the spinhuis and we can resolve this faster. This is a sad case of "works on all of our machines" so we're not sure what to respond here.

Also: You might just want to use the hosted versions of timbuctoo instead of running it yourself. Running it yourself is more for people who are changing the code. Check with Marnix for the urls to use.

**Comment by ericvanderlinden** [comment]
Klopt... Maar ik ben alleen op maandag of dinsdag in het spinhuis. Ik kan mijn computer niet meenemen, het is geen laptop.
Ik wil bovendien onder de motorkap kijken om me ook een beetje op React te orienteren en tegelijk Timbuctoo bekijken, nu we met de verhuis van Bioport bezig zijn.

Ik heb de install nu gedaan. Het is gelukt.

Ik denk door mijn gebrek aan ervaring met Node en NPM heb ik in eerste instantie niet gedacht aan het uitvoeren van npm install.
Daarna is dat install proces mis blijven gaan om dat de install werd uitgevoerd in mappen die ik al verwijdert had. 
Bij een install vanmorgen zag ik op de terminal opeens dat er modules in mijn trash werden geinstalleerd. In de trash stond een map timbuctoo-gui-develop die ik had verwijdert maar misschien heeft de teminal applicatie die op een of andere manier vastgehouden... Erg vreemd. 
Maar toen ik dat door had heb ik alles verwijdert, ook definitief in de trash. timbuctoo-gui-develop opnieuw van github gehaald en op mijn machine gezet.
en npm install uitgevoerd.

Misschien in de readme voor minder ervaren Node NPM gebruikers iets over npm install erbij vermelden.

Gelukt dus.
Nu de inlog nog :)
